kind: ConfigMap
apiVersion: v1
metadata:
  name: hellorest
  namespace: demo8
data:
  wavefront.tracing.enabled: "false"
  management.metrics.export.wavefront.enabled: "false"
  spring.sleuth.enabled: "false"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hellored
  namespace: demo8
data:
  wavefront.tracing.enabled: "false"
  management.metrics.export.wavefront.enabled: "false"
  spring.sleuth.enabled: "false"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hub
  namespace: demo8
data:
  wavefront.tracing.enabled: "false"
  management.metrics.export.wavefront.enabled: "false"
  spring.sleuth.enabled: "false"
  hub.urls: "http://service1/hello,http://service2/hello,http://service5"
