apiVersion: v1
kind: Service
metadata:
  labels:
    run: service1
  name: service1
  namespace: demo8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    run: helloworld
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service2
  name: service2
  namespace: demo8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    run: hellored
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service5
  name: service5
  namespace: demo8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: hello-python
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service6
  name: service6
  namespace: demo8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    run: hub
  type: ClusterIP
