apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: helloworld
  name: helloworld
  namespace: demo8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helloworld
  template:
    metadata:
      labels:
        run: helloworld
    spec:
      serviceAccountName: spring-service-account
      containers:
      - image: mhoshivm/spring-helloworld
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 8081
        env:
        - name: WAVEFRONT_FREEMIUM-ACCOUNT
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hellored
  name: hellored
  namespace: demo8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hellored
  template:
    metadata:
      labels:
        run: hellored
    spec:
      serviceAccountName: spring-service-account
      containers:
      - image: mhoshivm/spring-hellored
        imagePullPolicy: Always
        name: hellored
        ports:
        - containerPort: 8082
        env:
        - name: WAVEFRONT_FREEMIUM-ACCOUNT
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-python
  name: hello-python
  namespace: demo8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-python
  template:
    metadata:
      labels:
        run: hello-python
    spec:
      serviceAccountName: spring-service-account
      containers:
      - image: mhoshivm/hello-python
        imagePullPolicy: Always
        name: hello-python
        ports:
        - containerPort: 5000
        env:
        - name: WAVEFRONT_FREEMIUM-ACCOUNT
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hub
  name: hub
  namespace: demo8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hub
  template:
    metadata:
      labels:
        run: hub
    spec:
      serviceAccountName: spring-service-account
      containers:
      - image: mhoshivm/spring-hub
        imagePullPolicy: Always
        name: hub
        ports:
        - containerPort: 8086
        env:
        - name: WAVEFRONT_FREEMIUM-ACCOUNT
          value: "false"

