apiVersion: v1
kind: Service
metadata:
  labels:
    run: service1
  name: service1
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    run: service1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service2
  name: service2
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    run: service2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service6
  name: service6
  namespace: demo7
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    run: service6
  type: ClusterIP
